// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var activePic, changePicture, circleCount, j, pic_width, pics_count, prepareBG, randomPic, slider, sliderInner, _i;
    $('ul.items li').each(function(index) {
      return $(this).addClass("" + index);
    });
    slider = $(".items");
    sliderInner = slider.html();
    pic_width = 44;
    pics_count = parseInt(($(window).width() / 44).toFixed());
    circleCount = parseInt((pics_count / $('ul.items li').length).toFixed());
    activePic = ((pics_count / 2).toFixed()) - 1;
    console.log(pics_count, circleCount);
    for (j = _i = 0; 0 <= circleCount ? _i < circleCount : _i > circleCount; j = 0 <= circleCount ? ++_i : --_i) {
      slider.append(sliderInner);
    }
    changePicture = function() {
      if (window.showIndex < $('#photo-bg li').length - 1) {
        window.showIndex++;
      } else {
        window.showIndex = 0;
      }
      return $('#photo-bg li').removeClass('active').eq(window.showIndex).addClass('active');
    };
    prepareBG = function() {
      $('#photo-bg').find('li').eq(0).addClass('active');
      window.showIndex = 0;
      return setInterval(changePicture, 10000);
    };
    randomPic = function() {
      var count, curr, random;
      count = $('ul.items li').length;
      random = Math.floor(Math.random() * (count - 0 + 1));
      console.log(random);
      curr = $('ul.items li').eq(random);
      curr.clone().insertAfter($('ul.items li').eq(activePic));
      return curr.remove();
    };
    prepareBG();
    randomPic();
    $('ul.items li').removeClass('active').eq(activePic).addClass('active');
    $("html").keypress(function(event) {
      var p;
      if (event.which === 1102 || event.which === 46) {
        return $(".items li").eq(0).animate({
          "margin-left": -pic_width
        }, 300, function() {
          var p;
          p = $(this);
          p.clone().appendTo(slider).css({
            "margin-left": "0"
          });
          p.remove();
          return $('ul.items li').removeClass('active').eq(activePic).addClass('active');
        });
      } else if (event.which === 1073 || event.which === 44) {
        p = $(".items li").eq(-1);
        p.clone().css({
          "margin-left": -pic_width
        }).prependTo(slider).animate({
          "margin-left": 0
        }, 300, function() {
          return $('ul.items li').removeClass('active').eq(activePic).addClass('active');
        });
        return p.remove();
      }
    });
    return this;
  });

}).call(this);
